# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run:
          name: Run golangci-lint
          command: |
              go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0
              golangci-lint run

      - run:
          name: Run Go tests
          command: |
              go test ./...

  build-linux:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run:
          name: Create artifact upload directory and set variables
          command: |
              mkdir /tmp/upload
              echo 'export CINAME=$(sh contrib/semver/name.sh)' >> $BASH_ENV
              echo 'export CIVERSION=$(sh contrib/semver/version.sh --bare)' >> $BASH_ENV
              echo 'export CIVERSIONRPM=$(sh contrib/semver/version.sh --bare | tr "-" ".")' >> $BASH_ENV
              echo 'export CIBRANCH=$(echo $CIRCLE_BRANCH | tr -d "/")' >> $BASH_ENV
              case "$CINAME" in \
                "mesh") (echo 'export CICONFLICTS=mesh-develop' >> $BASH_ENV) ;; \
                "mesh-develop") (echo 'export CICONFLICTS=mesh' >> $BASH_ENV) ;; \
                *) (echo 'export CICONFLICTS="mesh mesh-develop"' >> $BASH_ENV) ;; \
              esac
              git config --global user.email "$(git log --format='%ae' HEAD -1)";
              git config --global user.name "$(git log --format='%an' HEAD -1)";

      - run:
          name: Install RPM utilities
          command: |
              sudo apt-get update
              sudo apt-get install -y rpm file
              mkdir -p ~/rpmbuild/BUILD ~/rpmbuild/RPMS ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/SRPMS

      - run:
          name: Test debug builds
          command: |
              ./build -d
              test -f mesh && test -f meshctl

      - run:
          name: Build for Linux (including Debian packages)
          command: |
              rm -f {mesh,meshctl}
              PKGARCH=amd64 sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-amd64 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-amd64;
              PKGARCH=i386 sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-i386 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-i386;
              PKGARCH=mipsel sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-mipsel && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-mipsel;
              PKGARCH=mips sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-mips && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-mips;
              PKGARCH=armhf sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-armhf && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-armhf;
              PKGARCH=armel sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-armel && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-armel;
              PKGARCH=arm64 sh contrib/deb/generate.sh && mv mesh /tmp/upload/$CINAME-$CIVERSION-linux-arm64 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-linux-arm64;
              mv *.deb /tmp/upload/

      - run:
          name: Build for Linux (RPM packages)
          command: |
              git clone https://github.com/RiV-chain/RiV-mesh-package-rpm ~/rpmbuild/SPECS
              cd ../ && tar -czvf ~/rpmbuild/SOURCES/v$CIVERSIONRPM --transform "s/project/RiV-mesh-$CIBRANCH-$CIVERSIONRPM/" project
              sed -i "s/RiV-mesh/RiV-mesh-$CIBRANCH/" ~/rpmbuild/SPECS/mesh.spec
              sed -i "s/^PKGNAME=mesh/PKGNAME=mesh-$CIBRANCH/" ~/rpmbuild/SPECS/mesh.spec
              sed -i "s/^Name\:.*/Name\:           $CINAME/" ~/rpmbuild/SPECS/mesh.spec
              sed -i "s/^Version\:.*/Version\:        $CIVERSIONRPM/" ~/rpmbuild/SPECS/mesh.spec
              sed -i "s/^Conflicts\:.*/Conflicts\:      $CICONFLICTS/" ~/rpmbuild/SPECS/mesh.spec
              cat ~/rpmbuild/SPECS/mesh.spec
              GOARCH=amd64 rpmbuild -v --nodeps --target=x86_64 -ba ~/rpmbuild/SPECS/mesh.spec
              #GOARCH=386 rpmbuild -v --nodeps --target=i386 -bb ~/rpmbuild/SPECS/mesh.spec
              find ~/rpmbuild/RPMS/ -name '*.rpm' -exec mv {} /tmp/upload \;
              find ~/rpmbuild/SRPMS/ -name '*.rpm' -exec mv {} /tmp/upload \;

      - run:
          name: Build for EdgeRouter and VyOS
          command: |
              rm -f {mesh,meshctl}
              git clone https://github.com/RiV-chain/vyatta-mesh /tmp/vyatta-mesh;
              cd /tmp/vyatta-mesh;
              BUILDDIR_RIV=$CIRCLE_WORKING_DIRECTORY ./build-edgerouter-x $CIRCLE_BRANCH;
              BUILDDIR_RIV=$CIRCLE_WORKING_DIRECTORY ./build-edgerouter-lite $CIRCLE_BRANCH;
              BUILDDIR_RIV=$CIRCLE_WORKING_DIRECTORY ./build-vyos-i386 $CIRCLE_BRANCH
              BUILDDIR_RIV=$CIRCLE_WORKING_DIRECTORY ./build-vyos-amd64 $CIRCLE_BRANCH
              mv *.deb /tmp/upload;

      - persist_to_workspace:
          root: /tmp
          paths:
            - upload

  build-macos:
    macos:
      xcode: "10.0.0"

    working_directory: ~/go/src/github.com/RiV-chain/RiV-mesh

    steps:
      - checkout

      - run:
          name: Create artifact upload directory and set variables
          command: |
              mkdir /tmp/upload
              echo 'export CINAME=$(sh contrib/semver/name.sh)' >> $BASH_ENV
              echo 'export CIVERSION=$(sh contrib/semver/version.sh --bare)' >> $BASH_ENV
              echo 'export PATH=$PATH:/usr/local/go/bin:~/go/bin' >> $BASH_ENV
              git config --global user.email "$(git log --format='%ae' HEAD -1)";
              git config --global user.name "$(git log --format='%an' HEAD -1)";
              echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - run:
          name: Install Go 1.16
          command: |
              cd /tmp
              curl -LO https://dl.google.com/go/go1.16.darwin-amd64.pkg
              sudo installer -pkg /tmp/go1.16.darwin-amd64.pkg -target /

      #- run:
      #    name: Install Gomobile
      #    command: |
      #        GO111MODULE=off go get golang.org/x/mobile/cmd/gomobile
      #        gomobile init

      - run:
          name: Build for macOS
          command: |
              GO111MODULE=on GOOS=darwin GOARCH=amd64 ./build
              cp mesh /tmp/upload/$CINAME-$CIVERSION-darwin-amd64
              cp meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-darwin-amd64;

      - run:
          name: Build for macOS (.pkg format)
          command: |
              PKGARCH=amd64 sh contrib/macos/create-pkg.sh
              mv *.pkg /tmp/upload/

      #- run:
      #    name: Build framework for iOS (.framework format)
      #    command: |
      #        sudo GO111MODULE=off go get -v github.com/RiV-chain/RiV-mesh/cmd/...
      #        sudo GO111MODULE=off go get -v github.com/RiV-chain/RiV-mesh/src/...
      #        GO111MODULE=off ./build -i
      #        mv *.framework /tmp/upload

      - persist_to_workspace:
          root: /tmp
          paths:
            - upload

  build-other:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run:
          name: Create artifact upload directory and set variables
          command: |
              mkdir /tmp/upload
              echo 'export CINAME=$(sh contrib/semver/name.sh)' >> $BASH_ENV
              echo 'export CIVERSION=$(sh contrib/semver/version.sh --bare)' >> $BASH_ENV
              git config --global user.email "$(git log --format='%ae' HEAD -1)";
              git config --global user.name "$(git log --format='%an' HEAD -1)";

      - run:
          name: Build for OpenBSD
          command: |
              rm -f {mesh,meshctl}
              GOOS=openbsd GOARCH=amd64 ./build && mv mesh /tmp/upload/$CINAME-$CIVERSION-openbsd-amd64 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-openbsd-amd64;
              GOOS=openbsd GOARCH=386 ./build && mv mesh /tmp/upload/$CINAME-$CIVERSION-openbsd-i386 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-openbsd-i386;

      - run:
          name: Build for FreeBSD
          command: |
              rm -f {mesh,meshctl}
              GOOS=freebsd GOARCH=amd64 ./build && mv mesh /tmp/upload/$CINAME-$CIVERSION-freebsd-amd64 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-freebsd-amd64;
              GOOS=freebsd GOARCH=386 ./build && mv mesh /tmp/upload/$CINAME-$CIVERSION-freebsd-i386 && mv meshctl /tmp/upload/$CINAME-$CIVERSION-meshctl-freebsd-i386;

      - run:
          name: Build for Windows
          command: |
              rm -f {mesh,meshctl}
              GOOS=windows GOARCH=amd64 ./build && mv mesh.exe /tmp/upload/$CINAME-$CIVERSION-windows-amd64.exe && mv meshctl.exe /tmp/upload/$CINAME-$CIVERSION-meshctl-windows-amd64.exe;
              GOOS=windows GOARCH=386 ./build && mv mesh.exe /tmp/upload/$CINAME-$CIVERSION-windows-i386.exe && mv meshctl.exe /tmp/upload/$CINAME-$CIVERSION-meshctl-windows-i386.exe;

      - persist_to_workspace:
          root: /tmp
          paths:
            - upload

  upload:
    machine: true

    steps:
      - attach_workspace:
          at: /tmp

      - store_artifacts:
          path: /tmp/upload
          destination: /

workflows:
  version: 2.1
  build:
    jobs:
      - lint
      - build-linux
      - build-macos
      - build-other
      - upload:
          requires:
            - build-linux
            - build-macos
            - build-other
