#!/bin/sh

export CONTENT_LENGTH=$HTTP_CONTENT_LENGTH
export CONTENT_TYPE=$HTTP_CONTENT_TYPE

#exit with zero status on auth success and 1 on error
[ ! -z $(/usr/syno/synoman/webman/modules/authenticate.cgi) ]
exit $?

